### ISSUE TITLE
Gettting No gcode at all.

### ISSUE THREAD

**Issue by nucleared** [flyfisher604/mpcnc_post_processor#10]
I am getting a blank file with no gcode at all when I select/enable both or either the Group 4 tool change and or the group  5 Z probing in Fusion 360. If I deselect them, then I get a complete gcode file. Not sure what is going on.

**Comment by flyfisher604** [comment]
Unsure why you would get no gcode at all. Possibly issue #12 caused bad characters to be inserted in the gcode file and your editor didn't want to open the file. Issue #12 should be fixed in the next release.

If this continues please provide more details.

**Comment by flyfisher604** [comment]
Please try version 2.0.1 or newer and see if it resolves your issue. If it doesn't please provide additional information.

**Comment by nucleared** [comment]
Thanks, I’ll try it later today.

**Comment by nucleared** [comment]
I've tested the 2.0.1 version on a small cute with both the tool change and the z probe and it works great!! Thanks
The only issue is the M0 comments do not display on the touch screen. I have to switch it to the line mode. Thats probably a Marlin issue, right?

**Comment by flyfisher604** [comment]
What screen are you using. I believe the message only appear if you are in Marlin mode, not the graphical mode.

**Comment by nucleared** [comment]
I'm using BIGTREETECH Direct TFT35 E3 V3.0. I thought that the M0 commands worked on both the Marlin mode and the Graphical one....are they working on fixing that or do I always have to switch to the Marlin Mode? Thanks for your help.
